services:
  app:  # Your app
    build: .
    ports:
      - "8080:8080"
    expose:
      - 8080
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres

  db:
    image: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
 
volumes:
  pgdata:
